import './globals.css'
import { Poppins } from 'next/font/google'
import { NextAuthProvider } from './Providers'

const inter = Poppins({ 
  subsets: ['latin'],
  weight:['100','200','300','400','500','600','700','800','900']
 })

export const metadata = {
  title: 'Organise IB',
  description: 'Generated by Organise IB',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
        {children}
        </NextAuthProvider>
        </body>
    </html>
  )
}
